![Piggy bank](piggy_bank.jpg)

Personal loans are a lucrative revenue stream for banks. The typical interest rate of a two-year loan in the United Kingdom is [around 10%](https://www.experian.com/blogs/ask-experian/whats-a-good-interest-rate-for-a-personal-loan/). This might not sound like a lot, but in September 2022 alone UK consumers borrowed [around £1.5 billion](https://www.ukfinance.org.uk/system/files/2022-12/Household%20Finance%20Review%202022%20Q3-%20Final.pdf), which would mean approximately £300 million in interest generated by banks over two years!

You have been asked to work with a bank to clean the data they collected as part of a recent marketing campaign, which aimed to get customers to take out a personal loan. They plan to conduct more marketing campaigns going forward so would like you to ensure it conforms to the specific structure and data types that they specify so that they can then use the cleaned data you provide to set up a PostgreSQL database, which will store this campaign's data and allow data from future campaigns to be easily imported.

They have supplied you with a csv file called `"bank_marketing.csv"`, which you will need to clean, reformat, and split the data, saving three final csv files. Specifically, the three files should have the names and contents as outlined below:

## `client.csv`

| column | data type | description | cleaning requirements |
|--------|-----------|-------------|-----------------------|
| `client_id` | `integer` | Client ID | N/A |
| `age` | `integer` | Client's age in years | N/A |
| `job` | `object` | Client's type of job | Change `"."` to `"_"` |
| `marital` | `object` | Client's marital status | N/A |
| `education` | `object` | Client's level of education | Change `"."` to `"_"` and `"unknown"` to `np.NaN` |
| `credit_default` | `bool` | Whether the client's credit is in default | Convert to boolean data type |
| `mortgage` | `bool` | Whether the client has an existing mortgage (housing loan) | Convert to boolean data type |

<br>

## `campaign.csv`

| column | data type | description | cleaning requirements |
|--------|-----------|-------------|-----------------------|
| `client_id` | `integer` | Client ID | N/A |
| `number_contacts` | `integer` | Number of contact attempts to the client in the current campaign | N/A |
| `contact_duration` | `integer` | Last contact duration in seconds | N/A |
| `previous_campaign_contacts` | `integer` | Number of contact attempts to the client in the previous campaign | N/A |
| `previous_outcome` | `bool` | Outcome of the previous campaign | Convert to boolean data type |
| `campaign_outcome` | `bool` | Outcome of the current campaign | Convert to boolean data type |
| `last_contact_date` | `datetime` | Last date the client was contacted | Create from a combination of `day`, `month`, and a newly created `year` column (which should have a value of `2022`); <br> **Format =** `"YYYY-MM-DD"` |

<br>

## `economics.csv`

| column | data type | description | cleaning requirements |
|--------|-----------|-------------|-----------------------|
| `client_id` | `integer` | Client ID | N/A |
| `cons_price_idx` | `float` | Consumer price index (monthly indicator) | N/A |
| `euribor_three_months` | `float` | Euro Interbank Offered Rate (euribor) three-month rate (daily indicator) | N/A |

MORE DETAILS AND INSTRUCTIONS:

Subset, clean, and reformat the bank_marketing.csv dataset to create and store three new files based on the requirements detailed in the notebook.

Split and tidy bank_marketing.csv, storing as three DataFrames called client, campaign, and economics, each containing the columns outlined in the notebook and formatted to the data types listed.

Save the three DataFrames to csv files, without an index, as client.csv, campaign.csv, and economics.csv respectively.

In [6]:
pip install pandas numpy

Requirement already satisfied: pandas in c:\users\sammu\anaconda3\lib\site-packages (2.0.3)
Requirement already satisfied: numpy in c:\users\sammu\anaconda3\lib\site-packages (1.24.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sammu\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\sammu\anaconda3\lib\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\sammu\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\sammu\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [22]:
import pandas as pd

# Load the dataset
df = pd.read_csv(r'C:/Users/sammu/Downloads/Project_1/bank_marketing.csv')

In [20]:
pip install pandas

Requirement already satisfied: pandas in c:\users\sammu\anaconda3\lib\site-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sammu\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\sammu\anaconda3\lib\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\sammu\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in c:\users\sammu\anaconda3\lib\site-packages (from pandas) (1.24.3)
Requirement already satisfied: six>=1.5 in c:\users\sammu\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [24]:
# Display the first few rows
print(df.head())
# Display summary information
print(df.info())

   client_id   age        job  marital    education credit_default mortgage  \
0          0  56.0  housemaid  married     basic.4y             no       no
1          1  57.0   services  married  high.school        unknown       no
2          2  37.0   services  married  high.school             no      yes
3          3  40.0     admin.  married     basic.6y             no       no
4          4  56.0   services  married  high.school             no       no

  month   day  contact_duration  number_contacts  previous_campaign_contacts  \
0   may  13.0             261.0              1.0                         0.0
1   may  19.0             149.0              1.0                         0.0
2   may  23.0             226.0              1.0                         0.0
3   may  27.0             151.0              1.0                         0.0
4   may   3.0             307.0              1.0                         0.0

  previous_outcome  cons_price_idx  euribor_three_months campaign_outcome
0      nonexistent          93.994                 4.857               no
1      nonexistent          93.994                 4.857               no
2      nonexistent          93.994                 4.857               no
3      nonexistent          93.994                 4.857               no
4      nonexistent          93.994                 4.857               no
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11692 entries, 0 to 11691
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   client_id                   11692 non-null  int64
 1   age                         11691 non-null  float64
 2   job                         11691 non-null  object
 3   marital                     11691 non-null  object
 4   education                   11691 non-null  object
 5   credit_default              11691 non-null  object
 6   mortgage                    11691 non-null  object
 7   month                       11691 non-null  object
 8   day                         11691 non-null  float64
 9   contact_duration            11691 non-null  float64
 10  number_contacts             11691 non-null  float64
 11  previous_campaign_contacts  11691 non-null  float64
 12  previous_outcome            11691 non-null  object
 13  cons_price_idx              11691 non-null  float64
 14  euribor_three_months        11691 non-null  float64
 15  campaign_outcome            11691 non-null  object
dtypes: float64(7), int64(1), object(8)
memory usage: 1.4+ MB
None

In [26]:
# Check missing values
print(df.isnull().sum())

# Example: Fill missing values or drop rows/columns
df['column_name'].fillna(df['column_name'].mode()[0], inplace=True)  # Fill with mode
# or
df.dropna(inplace=True)  # Drop missing rows

client_id                     0
age                           1
job                           1
marital                       1
education                     1
credit_default                1
mortgage                      1
month                         1
day                           1
contact_duration              1
number_contacts               1
previous_campaign_contacts    1
previous_outcome              1
cons_price_idx                1
euribor_three_months          1
campaign_outcome              1
dtype: int64

KeyError: 'column_name'

In [40]:
df = df.copy()  # Make a deep copy of df to avoid SettingWithCopyWarning

# Now you can safely fill missing values without warnings
df['job'].fillna(df['job'].mode()[0], inplace=True)

In [42]:
df['job'] = df['job'].fillna(df['job'].mode()[0])  # Reassigning without inplace

In [44]:
# Check missing values
print(df.isnull().sum())

# Fill missing values for categorical columns with the mode (most common value)
df['job'].fillna(df['job'].mode()[0], inplace=True)
df['marital'].fillna(df['marital'].mode()[0], inplace=True)
df['education'].fillna(df['education'].mode()[0], inplace=True)
df['credit_default'].fillna(df['credit_default'].mode()[0], inplace=True)
df['mortgage'].fillna(df['mortgage'].mode()[0], inplace=True)
df['month'].fillna(df['month'].mode()[0], inplace=True)
df['previous_outcome'].fillna(df['previous_outcome'].mode()[0], inplace=True)
df['campaign_outcome'].fillna(df['campaign_outcome'].mode()[0], inplace=True)

# Fill missing values for numerical columns with the median or mean
df['age'].fillna(df['age'].median(), inplace=True)
df['day'].fillna(df['day'].median(), inplace=True)
df['contact_duration'].fillna(df['contact_duration'].median(), inplace=True)
df['number_contacts'].fillna(df['number_contacts'].median(), inplace=True)
df['previous_campaign_contacts'].fillna(df['previous_campaign_contacts'].median(), inplace=True)
df['cons_price_idx'].fillna(df['cons_price_idx'].median(), inplace=True)
df['euribor_three_months'].fillna(df['euribor_three_months'].median(), inplace=True)

client_id                     0
age                           0
job                           0
marital                       0
education                     0
credit_default                0
mortgage                      0
month                         0
day                           0
contact_duration              0
number_contacts               0
previous_campaign_contacts    0
previous_outcome              0
cons_price_idx                0
euribor_three_months          0
campaign_outcome              0
dtype: int64

In [46]:
df.dropna(inplace=True)

In [52]:
# Define a year if not already included
year = 2024  # Replace with the actual year if known

# Create a date column from 'day' and 'month'
df['date_column'] = pd.to_datetime(df['day'].astype(int).astype(str) + '-' + df['month'] + '-' + str(year), format='%d-%b-%Y')

In [54]:
# Define a year (if the data does not include it already)
year = 2024  # Replace this with the actual year if known

# Step 1: Create a new column 'date_column' by combining 'day', 'month', and 'year'
df['date_column'] = pd.to_datetime(df['day'].astype(int).astype(str) + '-' + df['month'] + '-' + str(year), format='%d-%b-%Y')

# Step 2: Verify the creation of the 'date_column'
print(df[['day', 'month', 'date_column']].head())

    day month date_column
0  13.0   may  2024-05-13
1  19.0   may  2024-05-19
2  23.0   may  2024-05-23
3  27.0   may  2024-05-27
4   3.0   may  2024-05-03

In [56]:
# Check the first few rows to verify the new 'date_column'
print(df[['day', 'month', 'date_column']].head())

    day month date_column
0  13.0   may  2024-05-13
1  19.0   may  2024-05-19
2  23.0   may  2024-05-23
3  27.0   may  2024-05-27
4   3.0   may  2024-05-03

In [72]:
successful_campaigns.to_csv('successful_campaigns.csv', index=False)
failed_campaigns.to_csv('failed_campaigns.csv', index=False)

NameError: name 'successful_campaigns' is not defined

In [76]:
# Example assuming 'campaigns_df' is your main DataFrame and it has a 'status' column
successful_campaigns = campaigns_df[campaigns_df['status'] == 'successful']
failed_campaigns = campaigns_df[campaigns_df['status'] == 'failed']

NameError: name 'campaigns_df' is not defined

In [78]:
import pandas as pd

campaigns_df = pd.read_csv(r'C:/Users/sammu/Downloads/Project_1/bank_marketing.csv')  # Replace 'your_file.csv' with the actual file path

In [80]:
print(campaigns_df.head())  # Display the first few rows
print(campaigns_df.columns)  # List the column names

   client_id   age        job  marital    education credit_default mortgage  \
0          0  56.0  housemaid  married     basic.4y             no       no
1          1  57.0   services  married  high.school        unknown       no
2          2  37.0   services  married  high.school             no      yes
3          3  40.0     admin.  married     basic.6y             no       no
4          4  56.0   services  married  high.school             no       no

  month   day  contact_duration  number_contacts  previous_campaign_contacts  \
0   may  13.0             261.0              1.0                         0.0
1   may  19.0             149.0              1.0                         0.0
2   may  23.0             226.0              1.0                         0.0
3   may  27.0             151.0              1.0                         0.0
4   may   3.0             307.0              1.0                         0.0

  previous_outcome  cons_price_idx  euribor_three_months campaign_outcome
0      nonexistent          93.994                 4.857               no
1      nonexistent          93.994                 4.857               no
2      nonexistent          93.994                 4.857               no
3      nonexistent          93.994                 4.857               no
4      nonexistent          93.994                 4.857               no
Index(['client_id', 'age', 'job', 'marital', 'education', 'credit_default',
       'mortgage', 'month', 'day', 'contact_duration', 'number_contacts',
       'previous_campaign_contacts', 'previous_outcome', 'cons_price_idx',
       'euribor_three_months', 'campaign_outcome'],
      dtype='object')

In [84]:
print(campaigns_df.columns)

Index(['client_id', 'age', 'job', 'marital', 'education', 'credit_default',
       'mortgage', 'month', 'day', 'contact_duration', 'number_contacts',
       'previous_campaign_contacts', 'previous_outcome', 'cons_price_idx',
       'euribor_three_months', 'campaign_outcome'],
      dtype='object')

In [86]:
campaigns_df.columns = campaigns_df.columns.str.strip()

In [88]:
campaigns_df.rename(columns={'Status': 'status'}, inplace=True)

In [90]:
print(campaigns_df.head())

   client_id   age        job  marital    education credit_default mortgage  \
0          0  56.0  housemaid  married     basic.4y             no       no
1          1  57.0   services  married  high.school        unknown       no
2          2  37.0   services  married  high.school             no      yes
3          3  40.0     admin.  married     basic.6y             no       no
4          4  56.0   services  married  high.school             no       no

  month   day  contact_duration  number_contacts  previous_campaign_contacts  \
0   may  13.0             261.0              1.0                         0.0
1   may  19.0             149.0              1.0                         0.0
2   may  23.0             226.0              1.0                         0.0
3   may  27.0             151.0              1.0                         0.0
4   may   3.0             307.0              1.0                         0.0

  previous_outcome  cons_price_idx  euribor_three_months campaign_outcome
0      nonexistent          93.994                 4.857               no
1      nonexistent          93.994                 4.857               no
2      nonexistent          93.994                 4.857               no
3      nonexistent          93.994                 4.857               no
4      nonexistent          93.994                 4.857               no

In [94]:
print(campaigns_df.columns.tolist())

['client_id', 'age', 'job', 'marital', 'education', 'credit_default', 'mortgage', 'month', 'day', 'contact_duration', 'number_contacts', 'previous_campaign_contacts', 'previous_outcome', 'cons_price_idx', 'euribor_three_months', 'campaign_outcome']

In [96]:
print(campaigns_df.head())

   client_id   age        job  marital    education credit_default mortgage  \
0          0  56.0  housemaid  married     basic.4y             no       no
1          1  57.0   services  married  high.school        unknown       no
2          2  37.0   services  married  high.school             no      yes
3          3  40.0     admin.  married     basic.6y             no       no
4          4  56.0   services  married  high.school             no       no

  month   day  contact_duration  number_contacts  previous_campaign_contacts  \
0   may  13.0             261.0              1.0                         0.0
1   may  19.0             149.0              1.0                         0.0
2   may  23.0             226.0              1.0                         0.0
3   may  27.0             151.0              1.0                         0.0
4   may   3.0             307.0              1.0                         0.0

  previous_outcome  cons_price_idx  euribor_three_months campaign_outcome
0      nonexistent          93.994                 4.857               no
1      nonexistent          93.994                 4.857               no
2      nonexistent          93.994                 4.857               no
3      nonexistent          93.994                 4.857               no
4      nonexistent          93.994                 4.857               no

In [98]:
campaigns_df.columns = campaigns_df.columns.str.strip()

In [100]:
campaigns_df.rename(columns={'Status': 'status'}, inplace=True)

In [102]:
print(campaigns_df.dtypes)

client_id                       int64
age                           float64
job                            object
marital                        object
education                      object
credit_default                 object
mortgage                       object
month                          object
day                           float64
contact_duration              float64
number_contacts               float64
previous_campaign_contacts    float64
previous_outcome               object
cons_price_idx                float64
euribor_three_months          float64
campaign_outcome               object
dtype: object

In [106]:
print("Columns:", campaigns_df.columns)
print("Data types:\n", campaigns_df.dtypes)

Columns: Index(['client_id', 'age', 'job', 'marital', 'education', 'credit_default',
       'mortgage', 'month', 'day', 'contact_duration', 'number_contacts',
       'previous_campaign_contacts', 'previous_outcome', 'cons_price_idx',
       'euribor_three_months', 'campaign_outcome'],
      dtype='object')
Data types:
 client_id                       int64
age                           float64
job                            object
marital                        object
education                      object
credit_default                 object
mortgage                       object
month                          object
day                           float64
contact_duration              float64
number_contacts               float64
previous_campaign_contacts    float64
previous_outcome               object
cons_price_idx                float64
euribor_three_months          float64
campaign_outcome               object
dtype: object

In [108]:
print(campaigns_df.head())

   client_id   age        job  marital    education credit_default mortgage  \
0          0  56.0  housemaid  married     basic.4y             no       no
1          1  57.0   services  married  high.school        unknown       no
2          2  37.0   services  married  high.school             no      yes
3          3  40.0     admin.  married     basic.6y             no       no
4          4  56.0   services  married  high.school             no       no

  month   day  contact_duration  number_contacts  previous_campaign_contacts  \
0   may  13.0             261.0              1.0                         0.0
1   may  19.0             149.0              1.0                         0.0
2   may  23.0             226.0              1.0                         0.0
3   may  27.0             151.0              1.0                         0.0
4   may   3.0             307.0              1.0                         0.0

  previous_outcome  cons_price_idx  euribor_three_months campaign_outcome
0      nonexistent          93.994                 4.857               no
1      nonexistent          93.994                 4.857               no
2      nonexistent          93.994                 4.857               no
3      nonexistent          93.994                 4.857               no
4      nonexistent          93.994                 4.857               no

In [110]:
campaigns_df.columns = campaigns_df.columns.str.strip()

In [112]:
campaigns_df.rename(columns={'actual_column_name': 'status'}, inplace=True)  # Replace 'actual_column_name' with the exact name found

In [116]:
print("Columns in campaigns_df:", campaigns_df.columns.tolist())

Columns in campaigns_df: ['client_id', 'age', 'job', 'marital', 'education', 'credit_default', 'mortgage', 'month', 'day', 'contact_duration', 'number_contacts', 'previous_campaign_contacts', 'previous_outcome', 'cons_price_idx', 'euribor_three_months', 'campaign_outcome']

In [118]:
print(campaigns_df.head())

   client_id   age        job  marital    education credit_default mortgage  \
0          0  56.0  housemaid  married     basic.4y             no       no
1          1  57.0   services  married  high.school        unknown       no
2          2  37.0   services  married  high.school             no      yes
3          3  40.0     admin.  married     basic.6y             no       no
4          4  56.0   services  married  high.school             no       no

  month   day  contact_duration  number_contacts  previous_campaign_contacts  \
0   may  13.0             261.0              1.0                         0.0
1   may  19.0             149.0              1.0                         0.0
2   may  23.0             226.0              1.0                         0.0
3   may  27.0             151.0              1.0                         0.0
4   may   3.0             307.0              1.0                         0.0

  previous_outcome  cons_price_idx  euribor_three_months campaign_outcome
0      nonexistent          93.994                 4.857               no
1      nonexistent          93.994                 4.857               no
2      nonexistent          93.994                 4.857               no
3      nonexistent          93.994                 4.857               no
4      nonexistent          93.994                 4.857               no

In [124]:
# Split the data into successful and failed campaigns
successful_campaigns = df[df['campaign_outcome'] == 'yes']
failed_campaigns = df[df['campaign_outcome'] == 'no']

# Optional: Verify the split by checking the counts
print("Successful Campaigns:", successful_campaigns.shape[0])
print("Failed Campaigns:", failed_campaigns.shape[0])

Successful Campaigns: 408
Failed Campaigns: 11283

In [126]:
# Save successful campaigns to a CSV file
successful_campaigns.to_csv('successful_campaigns.csv', index=False)

# Save failed campaigns to a CSV file
failed_campaigns.to_csv('failed_campaigns.csv', index=False)